name: co19_primary_constructors
description: co19 tests for Primary constructors feature

# These tests aren't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  meta: ^1.18.2
